### ISSUE TITLE
Date missing on ADP command

### ISSUE THREAD

**Issue by chrisparsons83** [chrisparsons83/FFDiscordBot#132]
Current, a command like !adp Kyler Murray does this:

ADP as of  via 4for4 for Kyler Murray: ESPN: 106, MFL: 122, NFL: 124, Yahoo: 91

It should say:

ADP as of July 10, 2019 via 4for4 for Kyler Murray: ESPN: 106, MFL: 122, NFL: 124, Yahoo: 91

**Comment by tc216997** [comment]
This should be fixed with the latest pull request using moment.js lib.
